### ISSUE TITLE
Outdated Image

### ISSUE THREAD

**Issue by rsleiberin** [learn-co-curriculum/phase-0-getting-code-with-git#3]
### Canvas Link

https://learning.flatironschool.com/courses/5166/pages/getting-code-with-git?module_item_id=341586

### Concern

The image for switching to SSH from the URL format on the *Code* button of github is outdated.

### Additional Context

Canvas:

https://curriculum-content.s3.amazonaws.com/git-clone-using-ssh.png

Actual:
https://cdn.discordapp.com/attachments/736041413615157268/926487824902012958/unknown.png

### Suggested Changes

Update image with current version.

**Comment by lizbur10** [comment]
Hi @rsleiberin ! Thanks for bringing this to our attention.

The image has been updated to reflect the current UI in GitHub. Note that you may not see the change on your Canvas course page, but it will be present for students moving forward.

Thanks for contributing to the Flatiron School curriculum 💙
